
const headerParse = require('header-parse');

/**
 * Convert header names to lower case and normalize value to string.
 * @param {Object} headers  - Key/value object of headers
 * @return {Object}         - Normalized headers
 */
const normalizedHeaders = (headers) => {
    var normalized = {};
    Object.keys(headers).forEach((key) => {
        normalized[key.toLowerCase()] = '' + [headers[key]];
    });
    return normalized;
}

/**
 * Check if email is autoreply according to headers.
 * @param {Object} headers  - Email headers as key/value object
 * @return {Boolean}        - True if autoreply, false otherwise
 */
module.exports = (headers) => {

    if (!headers) {
        return false;
    }

    if(typeof headers === 'string' || Buffer.isBuffer(headers)) {
        headers = headerParse.parseHeaders(headers);
    }

    headers = normalizedHeaders(headers);

    // Detections according to <https://github.com/jpmckinney/multi_mail/wiki/Detecting-autoresponders>
    if ('auto-submitted' in headers && headers['auto-submitted'].toLowerCase() !== 'no') {
        return true;
    }
    if ('return-path' in headers && headers['return-path'] === '<>') {
        return true;
    }
    if (headers['preference'] === 'auto_reply' || headers['preference'] === 'bulk' || headers['x-preference'] === 'auto_reply' || 'x-autorespond' in headers) {
        return true;
    }
    if ('x-autogenerated' in headers && ['forward', 'group', 'letter', 'mirror', 'redirect', 'reply'].includes(headers['x-autogenerated'].toLowerCase())) {
        return true;
    }
    if ('x-mail-autoreply' in headers || 'x-autoreply-from' in headers) {
        return true;
    }
    if ('x-fc-machinegenerated' in headers && headers['x-fc-machinegenerated'].toLowerCase() === 'true') {
        return true;
    }
    if ('precedence' in headers && headers['precedence'].toLowerCase() === 'bulk') {
        return true;
    }
    if ('x-autoreply' in headers && headers['x-autoreply'].toLowerCase() === 'yes') {
        return true;
    }
    if ('x-post-messageclass' in headers && headers['x-post-messageclass'].toLowerCase() === '9; autoresponder') {
        return true;
    }
    if ('delivered-to' in headers && headers['delivered-to'].toLowerCase() === 'autoresponder') {
        return true;
    }

    // Detecting MS Exchange/Outlook according to <https://msdn.microsoft.com/en-us/library/ee219609(v=exchg.80).aspx>
    if ('x-auto-response-suppress' in headers && headers['x-auto-response-suppress'].toLowerCase() !== 'none') {
        return true;
    }

    // By default email is not autoreply
    return false;
};
